---
- name: Install htop
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:
    - name: Includes users
      ansible.builtin.include_tasks: tasks/users.yml
    - name: Includes cron
      ansible.builtin.include_tasks: tasks/cron.yml
    - name: Includes the required packages
      ansible.builtin.include_tasks: tasks/packages.yml
