#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false # multipass will handle the reboot if necessary (?)

timezone: America/Sao_Paulo

packages:
  - curl
  - git
  # Ansible PPA
  - software-properties-common 

apt:
  sources:
    ansible-ppa:
      source: "ppa:ansible/ansible"

final_message: "System is up after $UPTIME seconds"
