#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false # multipass will handle the reboot if necessary (?)

timezone: America/Sao_Paulo

apt:
  sources:
    ansible-ppa:
      source: "ppa:ansible/ansible"
    veracrypt-ppa:
      source: "ppa:unit193/encryption"

packages:
  - curl
  - git
  - software-properties-common
  - ansible
  - veracrypt

runcmd:
  - [ sh, -c, "curl -fsSL https://get.docker.com -o get-docker.sh" ]
  - [ sh, get-docker.sh ]
  - [ systemctl, enable, --now, docker ]
  - [ usermod, -aG, docker, ubuntu ]

final_message: "System is up after $UPTIME seconds"
